storage:
  storage_path: /qdrant/storage

service:
  http_port: 6333
  grpc_port: 6334

# Collections à créer au démarrage
collections:
  documents:
    vectors:
      size: 1536
      distance: "Cosine"
    replication_factor: 1